---
- name: Fetch configurations from NetBox and push to GitHub
  hosts: localhost
  gather_facts: yes
  vars:
    current_date: "{{ ansible_date_time.date | replace('-', '') }}" # Format as YYYYMMDD
    current_time: "{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"  # Format as HHMM
    output_dir: "/home/user1/netbox_data"
    git_repo_path: "/home/user1/netbox_fetch_push/"
    xlsx_file: "{{ output_dir }}/netbox_data-{{ current_date }}-{{ current_time }}.xlsx"
    script_path: "convert_json_to_xlsx.py"
    htmltopdf_script_path: "convert_html_to_pdf.py"

  tasks:
    - name: Ensure output directory exists
      file:
        path: "{{ output_dir }}"
        state: directory

    - name: Ensure the git repository directory exists
      file:
        path: "{{ git_repo_path }}"
        state: directory

    - name: Clone the repository if not present
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_repo_path }}"
        version: main
        accept_hostkey: true

    - name: Fetch sites from NetBox
      uri:
        url: "{{ netbox_api_url }}dcim/sites/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_sites

    - name: Fetch devices from NetBox
      uri:
        url: "{{ netbox_api_url }}dcim/devices/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_devices

    - name: Fetch racks from NetBox
      uri:
        url: "{{ netbox_api_url }}dcim/racks/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_racks

    - name: Save configurations to JSON file
      copy:
        content: |
          {
            "devices": {{ netbox_devices.content | to_nice_json }},
            "sites": {{ netbox_sites.content | to_nice_json }},
            "racks": {{ netbox_racks.content | to_nice_json }}
          }
        dest: "{{ output_dir }}/netbox_data-{{ current_date }}-{{ current_time }}.json"
        mode: '0644'
      register: json_save_result
      failed_when: json_save_result is not defined

    - name: Copy JSON file to repository directory
      copy:
        src: "{{ output_dir }}/netbox_data-{{ current_date }}-{{ current_time }}.json"
        dest: "{{ git_repo_path }}"
      register: copy_json_result

    - name: Convert JSON to XLSX
      command: "python3 {{ script_path }} {{ output_dir }}/netbox_data-{{ current_date }}-{{ current_time }}.json {{ xlsx_file }}"

    - name: Configure Git user
      command:
        cmd: git config --global user.name "{{ git_username }}"
        chdir: "{{ git_repo_path }}"
    
    - name: Configure Git email
      command:
        cmd: git config --global user.email "{{ git_useremail }}"
        chdir: "{{ git_repo_path }}"

    - name: Copy JSON, HTML, PDF, and XLSX files to repository directory
      copy:
        src: "{{ item }}"
        dest: "{{ git_repo_path }}"
      loop:
        - "{{ output_dir }}/netbox_data-{{ current_date }}-{{ current_time }}.json"
        - "{{ xlsx_file }}"
      register: copy_files_result

    - name: Add new files to git
      command:
        cmd: git add .
        chdir: "{{ git_repo_path }}"

    - name: Commit changes to git
      command:
        cmd: git commit -m "Add NetBox data" --allow-empty
        chdir: "{{ git_repo_path }}"
      ignore_errors: yes

    - name: Push changes to GitHub
      command:
        cmd: git push
        chdir: "{{ git_repo_path }}"
      ignore_errors: yes
