---
- name: Fetch configurations from NetBox and push to GitHub
  hosts: localhost
  gather_facts: yes
  vars:
    target_host: "node3"
    current_date: "{{ ansible_date_time.date | replace('-', '') }}" # Format as YYYYMMDD
    current_time: "{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"  # Format as HHMM
    netbox_api_url: "https://mnqh6527.cloud.netboxapp.com/api/"
    netbox_token: "7e1c591e544353bedaeba2fdca5309ff16dfe268"
    github_token: "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"
    git_repo_url: "git@github.com:ayoemman/test01.git"
    git_username: "ayoemman"
    git_useremail: "ayoemman006@gmail.com"
    output_dir: "/home/user1/netbox_data"
    git_repo_path: "/home/user1/netbox_fetch_push/"
    html_file: "{{ output_dir }}/netbox_data.html"
    pdf_file: "{{ output_dir }}/netbox_data.pdf"
    xlsx_file: "{{ output_dir }}/netbox_data.xlsx"
    script_path: "convert_json_to_xlsx.py"

  tasks:
    - name: Ensure output directory exists
      file:
        path: "{{ output_dir }}"
        state: directory

    - name: Ensure the git repository directory exists
      file:
        path: "{{ git_repo_path }}"
        state: directory

    - name: Clone the repository if not present
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_repo_path }}"
        version: main
        accept_hostkey: true

    - name: Fetch sites from NetBox
      uri:
        url: "{{ netbox_api_url }}dcim/sites/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_sites

    - name: Fetch devices from NetBox
      uri:
        url: "{{ netbox_api_url }}dcim/devices/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_devices

    - name: Fetch racks from NetBox
      uri:
        url: "{{ netbox_api_url }}dcim/racks/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_racks

    - name: Save configurations to JSON file
      copy:
        content: |
          {
            "devices": {{ netbox_devices.content | to_nice_json }},
            "sites": {{ netbox_sites.content | to_nice_json }},
            "racks": {{ netbox_racks.content | to_nice_json }}
          }
        dest: "{{ output_dir }}/netbox_data-{{ current_date }}-{{ current_time }}.json"
        mode: '0644'
      delegate_to: "{{ target_host }}"
      register: json_save_result
      failed_when: json_save_result is not defined
