---
- name: Fetch data from NetBox and push to GitHub
  hosts: localhost
  gather_facts: no
  vars:
    netbox_api_url: "https://mnqh6527.cloud.netboxapp.com/api/"
    netbox_token: "7e1c591e544353bedaeba2fdca5309ff16dfe268"
    output_dir: "/home/user1/netbox_data"
    git_repo_path: "/home/user1/netbox_fetch_push/"
    github_token: "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"
    git_repo_url: "https://{{ github_token }}@github.com/ayoemman/netboxinventory_1.git"

  tasks:
    - name: Ensure output directory exists
      ansible.builtin.file:
        path: "{{ output_dir }}"
        state: directory

    - name: Ensure the git repository directory exists
      ansible.builtin.file:
        path: "{{ git_repo_path }}"
        state: directory

    - name: Clone the repository if not present
      ansible.builtin.git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_repo_path }}"
        version: main
        update: yes
    
    - name: Check if 'origin' remote is already configured
      ansible.builtin.command:
        cmd: git remote get-url origin
        chdir: "{{ git_repo_path }}"
      register: git_remote_status
      failed_when: false
      changed_when: false

    - name: Fetch sites from NetBox
      ansible.builtin.uri:
        url: "{{ netbox_api_url }}dcim/sites/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_sites

    - name: Write sites data to file
      ansible.builtin.copy:
        content: "{{ netbox_sites.content | to_nice_yaml }}"
        dest: "{{ output_dir }}/sites.yml"
      when: netbox_sites.status == 200
    
    - name: Change to the git repository directory
      ansible.builtin.command:
        cmd: git status
        chdir: "{{ git_repo_path }}"

    - name: Add remote repository if not present
      ansible.builtin.command:
        cmd: git remote add origin {{ git_repo_url }}
        chdir: "{{ git_repo_path }}"
      when: git_remote_status.failed

    - name: Configure Git user
      ansible.builtin.command:
        cmd: git config --global user.name "ayoemman"
        chdir: "{{ git_repo_path }}"
      
    - name: Configure Git email
      ansible.builtin.command:
        cmd: git config --global user.email "ayoemman006@gmail.com"
        chdir: "{{ git_repo_path }}"

    - name: Add new files to git
      ansible.builtin.command:
        cmd: git add .
        chdir: "{{ git_repo_path }}"

    - name: Commit changes to git
      ansible.builtin.command:
        cmd: git commit -m "Add NetBox data"
        chdir: "{{ git_repo_path }}"
      ignore_errors: yes

    - name: Push changes to GitHub
      ansible.builtin.command:
        cmd: git push -u origin main
        chdir: "{{ git_repo_path }}"
      ignore_errors: yes
