---
- name: Fetch data from NetBox and push to GitHub
  hosts: localhost
  gather_facts: no
  vars:
    netbox_api_url: "https://mnqh6527.cloud.netboxapp.com/api/"
    netbox_token: "7e1c591e544353bedaeba2fdca5309ff16dfe268"
    output_dir: "/home/user1/netbox_data"
    git_repo_path: "/home/user1/netbox_fetch_push/"
    github_token: "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"
    git_repo_url: "git@github.com:ayoemman/netboxinventory_1.git"

  tasks:
    - name: Ensure output directory exists
      file:
        path: "{{ output_dir }}"
        state: directory

    - name: Ensure the git repository directory exists
      file:
        path: "{{ git_repo_path }}"
        state: directory

    - name: Clone the repository if not present
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_repo_path }}"
        version: main
        accept_hostkey: true

    - name: Fetch sites from NetBox
      uri:
        url: "{{ netbox_api_url }}dcim/sites/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_sites

    - name: Write sites data to file
      copy:
        content: "{{ netbox_sites.content | to_nice_yaml }}"
        dest: "{{ output_dir }}/sites22.yml"
      when: netbox_sites.status == 200

    - name: Copy sites.yml to the repository directory
      copy:
        src: "{{ output_dir }}/sites22.yml"
        dest: "{{ git_repo_path }}/sites22.yml"

    - name: Add specific file to git
      command:
        cmd: git add sites.yml
        chdir: "{{ git_repo_path }}"

    - name: Commit changes to git
      command:
        cmd: git commit -m "Add NetBox data" --allow-empty
        chdir: "{{ git_repo_path }}"
      ignore_errors: yes

    - name: Push changes to GitHub
      command:
        cmd: git push
        chdir: "{{ git_repo_path }}"
      ignore_errors: yes
