- name: Fetch data from NetBox and push to GitHub
  hosts: localhost
  gather_facts: no
  vars:
    netbox_api_url: "https://mnqh6527.cloud.netboxapp.com/api/"
    netbox_token: "7e1c591e544353bedaeba2fdca5309ff16dfe268"
    output_dir: "/home/user1/netbox_data"
    git_repo_path: "/home/user1/netbox_fetch_push/"
    github_token: "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"
    git_repo_url: "https://github.com/ayoemman/netboxinventory_1.git"

  tasks:
    - name: Ensure output directory exists
      file:
        path: "{{ output_dir }}"
        state: directory

    - name: Ensure the git repository directory exists
      file:
        path: "{{ git_repo_path }}"
        state: directory

    - name: Clone the repository if not present
      git:
        repo: "https://github.com/ayoemman/netbox_fetch_push.git"
        dest: "{{ git_repo_path }}"
        version: main
        update: yes
    
    - name: Check if 'origin' remote is already configured
      command: git remote get-url origin
      args:
        chdir: "{{ git_repo_path }}"
      register: git_remote_status
      failed_when: false
      changed_when: false

    - name: Fetch sites from NetBox
      uri:
        url: "{{ netbox_api_url }}dcim/sites/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_sites

    - name: Write sites data to file
      copy:
        content: "{{ netbox_sites.content | to_nice_yaml }}"
        dest: "{{ output_dir }}/sites.yml"
      when: netbox_sites.status == 200
    
    - name: Change to the git repository directory
      command: chdir={{ git_repo_path }} git status

    - name: Add remote repository if not present
      command:
        cmd: git remote add origin https://ayoemman@github.com/ayoemman/netboxinventory_1.git
        chdir: "{{ git_repo_path }}"
      when: git_remote_status.failed

    - name: Configure Git user
      command:
        cmd: git config --global user.name "ayoemman"
        chdir: "{{ git_repo_path }}"
      
    - name: Configure Git email
      command:
        cmd: git config --global user.email "ayoemman006@gmail.com"
        chdir: "{{ git_repo_path }}"

    - name: Add new files to git
      command:
        cmd: git add .
        chdir: "{{ git_repo_path }}"

    - name: Commit changes to git
      command:
        cmd: git commit -m "Add NetBox data"
        chdir: "{{ git_repo_path }}"
      ignore_errors: yes

    - name: Push changes to GitHub
      environment:
        GIT_ASKPASS: /bin/echo
        GITHUB_TOKEN: "{{ github_token }}"
      command:
        cmd: git push
        chdir: "{{ git_repo_path }}"
      ignore_errors: yes
      register: git_push_result

    - name: Debug push result
      debug:
        var: git_push_result
