---
- name: Fetch data from NetBox and push to GitHub
  hosts: localhost
  gather_facts: no
  vars:
    netbox_api_url: "https://mnqh6527.cloud.netboxapp.com/api/"
    netbox_token: "7e1c591e544353bedaeba2fdca5309ff16dfe268"
    output_dir: "/home/user1/netbox_data"
    git_repo_path: "/home/user1/netbox_fetch_push/"
    github_token: "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"
    git_repo_url: "https://ayoemman:{{ github_token }}@github.com/ayoemman/netboxinventory_1.git"

  tasks:
    - name: Ensure output directory exists
      file:
        path: "{{ output_dir }}"
        state: directory

    - name: Fetch sites from NetBox
      uri:
        url: "{{ netbox_api_url }}dcim/sites/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_sites

    - name: Write sites data to file
      copy:
        content: "{{ netbox_sites.content | to_nice_yaml }}"
        dest: "{{ output_dir }}/sites.yml"
      when: netbox_sites.status == 200

    - name: Change to the git repository directory
      command: chdir={{ git_repo_path }} git status

    - name: Add remote repository if not present
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_repo_path }}"
        version: master
        state: present
      when: "'origin' not in (chdir={{ git_repo_path }} git remote) else skip"

    - name: Configure Git user
      git_config:
        name: "ayoemman"
        email: "ayoemman006@gmail.com"
        scope: global

    - name: Add new files to git
      command: chdir={{ git_repo_path }} git add .
      ignore_errors: yes

    - name: Commit changes to git
      command: chdir={{ git_repo_path }} git commit -m "Add NetBox data"
      ignore_errors: yes

    - name: Push changes to GitHub
      command: chdir={{ git_repo_path }} git push
      ignore_errors: yes
