---
- name: Fetch data from NetBox and push to GitHub
  hosts: localhost
  gather_facts: no
  vars:
    netbox_api_url: "https://mnqh6527.cloud.netboxapp.com/api/"
    netbox_token: "7e1c591e544353bedaeba2fdca5309ff16dfe268"
    output_dir: "/home/user1/netbox_data"
    git_repo_path: "/home/user1/netbox_fetch_push/"
    git_repo_url: "git@github.com:ayoemman/netboxinventory_1.git"

  tasks:
    - name: Ensure output directory exists
      file:
        path: "{{ output_dir }}"
        state: directory

    - name: Ensure the git repository directory exists
      file:
        path: "{{ git_repo_path }}"
        state: directory

    - name: Clone the repository if not present
      git:
        repo: "{{ git_repo_url }}"
        dest: "{{ git_repo_path }}"
        version: main
        update: yes
        accept_hostkey: true

    - name: Fetch sites from NetBox
      uri:
        url: "{{ netbox_api_url }}dcim/sites/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_sites

    - name: Write sites data to file
      copy:
        content: "{{ netbox_sites.content | to_nice_yaml }}"
        dest: "{{ output_dir }}/sites.yml"
      when: netbox_sites.status == 200

    - name: Change to the git repository directory
      command:
        cmd: git status
        chdir: "{{ git_repo_path }}"

    - name: Configure Git user
      command:
        cmd: git config --global user.name "ayoemman"
        chdir: "{{ git_repo_path }}"
      
    - name: Configure Git email
      command:
        cmd: git config --global user.email "ayoemman006@gmail.com"
        chdir: "{{ git_repo_path }}"

    - name: Copy sites.yml to the repository directory
      copy:
        src: "{{ output_dir }}/sites.yml"
        dest: "{{ git_repo_path }}/sites.yml"
        
    - name: Add new files to git
      command:
        cmd: git add sites.yml
        chdir: "{{ git_repo_path }}"

    - name: Check for changes to commit
      command:
        cmd: git status --porcelain
        chdir: "{{ git_repo_path }}"
      register: git_status_result

    - name: Debug Git Status
      debug:
        var: git_status_result.stdout_lines

    - name: Commit changes to git
      command:
        cmd: git commit -m "Add NetBox data" --allow-empty
        chdir: "{{ git_repo_path }}"
      register: git_commit_result

    - name: Debug commit result
      debug:
        var: git_commit_result

    - name: Push changes to GitHub
      command:
        cmd: git push
        chdir: "{{ git_repo_path }}"
      register: git_push_result

    - name: Debug push result
      debug:
        var: git_push_result
